// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWyfzXIzFDYD46wCK7LcmeRRzDOg3e4s',
    appId: '1:49768949748:web:a0914e388497a04612fba1',
    messagingSenderId: '49768949748',
    projectId: 'cu-book-8e865',
    authDomain: 'cu-book-8e865.firebaseapp.com',
    databaseURL: 'https://cu-book-8e865-default-rtdb.firebaseio.com',
    storageBucket: 'cu-book-8e865.appspot.com',
    measurementId: 'G-1LXH4V0DVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOWyfzXIzFDYD46wCK7LcmeRRzDOg3e4s',
    appId: '1:49768949748:android:461529885f6b140612fba1',
    messagingSenderId: '49768949748',
    projectId: 'cu-book-8e865',
    databaseURL: 'https://cu-book-8e865-default-rtdb.firebaseio.com',
    storageBucket: 'cu-book-8e865.appspot.com',
  );
}
